Repository Workiva/dart_dev, pull requests merged in 2022-07, with the labels that each got.

#380 Update to latest image of github ci verifier
  skynet.yaml
Labels: Merge Requirements Met, semver: patch, RM Ready

#384 Update docs tests to use `dart analyze`
  test/functional/documentation_test.dart
Labels: Merge Requirements Met, semver: patch, RM Ready

#383 RM-126419 Release dart_dev 3.7.2
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#382 Add import sorting to format tool
  CHANGELOG.md
  dart_dependency_validator.yaml
  doc/tools/format-tool.md
  lib/src/dart_dev_runner.dart
  lib/src/tools/format_tool.dart
  lib/src/tools/function_tool.dart
  lib/src/tools/test_tool.dart
  lib/src/tools/webdev_serve_tool.dart
  lib/src/utils/organize_directives/namespace.dart
  lib/src/utils/organize_directives/namespace_collector.dart
  lib/src/utils/organize_directives/organize_directives.dart
  lib/src/utils/organize_directives/organize_directives_in_paths.dart
  lib/src/utils/run_process_and_ensure_exit.dart
  lib/src/utils/start_process_and_ensure_exit.dart
  lib/utils.dart
  pubspec.yaml
  test/functional/fixtures/format/unsorted_imports/organize_directives_off/lib/main.dart
  test/functional/fixtures/format/unsorted_imports/organize_directives_off/pubspec.yaml
  test/functional/fixtures/format/unsorted_imports/organize_directives_off/tool/dart_dev/config.dart
  test/functional/fixtures/format/unsorted_imports/organize_directives_on/lib/main.dart
  test/functional/fixtures/format/unsorted_imports/organize_directives_on/pubspec.yaml
  test/functional/fixtures/format/unsorted_imports/organize_directives_on/tool/dart_dev/config.dart
  test/functional/format_tool_functional_test.dart
  test/tools/analyze_tool_test.dart
  test/tools/fixtures/organize_directives/directives.dart
  test/tools/format_tool_test.dart
  test/tools/shared_tool_tests.dart
  test/tools/test_tool_test.dart
  test/tools/webdev_serve_tool_test.dart
  test/utils/assert_no_positional_args_before_separator_test.dart
  test/utils/format_tool_builder_test.dart
  test/utils/organize_imports/organize_directives_test.dart
  tool/dart_dev/config.dart
Labels: Merge Requirements Met, semver: minor, RM Ready
