Repository Workiva/dart_dev, pull requests merged in 2023-11, with the labels that each got.

#420 FEDX-518 Now that dart_dev itself is null-safe, it should be able to generate a null-safe run script
  CHANGELOG.md
  lib/src/executable.dart
Labels: Merge Requirements Met, semver: patch, RM Ready

#421 RM-211323 Release dart_dev 4.0.3
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#422 FEDX-519 Raise maximum SDK to include Dart 3 and update CI
  .github/workflows/ci.yml
  .github/workflows/dart_ci.yml
  CHANGELOG.md
  pubspec.yaml
  test/functional/null_safety_functional_test.dart
Labels: Merge Requirements Met, semver: minor, RM Ready

#423 RM-223351 Release dart_dev 4.1.0
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready
